### ISSUE TITLE
Dose averaging should be done with physical dose, not kinetic energy.

### ISSUE THREAD

**Issue by laegdsmand** [Villadslj/Topas-Extension#8]
https://github.com/Villadslj/Topas-Extension/blob/4d128b9bcce5721d8f45fbdf17cdb2b9fe96b183/topas_extensions/Qeff.cc#L99

**Comment by grzanka** [comment]
I agree !

**Comment by Villadslj** [comment]
Yes that is true, I have corrected that now. 

I also found an issue (that Maria pointed me to).
Where we get a lot of nan value for Qeff. This happens if the particle loses all its energy in the step. in which case the kinetic energy of the particle is 0 and hence Qeff becomes nan. 

Right now I have fixed this by adding a line, to check is the energy of the particle is 0 then the deposited energy in that step must by the same as the kinetic energy. 

What do you think of this?

**Comment by laegdsmand** [comment]
Looks good. Nice job Villads.
We still have some problems with the scale of the Qeff values which is off by many orders of magnitude. When printing out the values for Qeff, Zeff and beta of individual hits, it looks very reasonable. So maybe there is still an issue with the denominator or averaging?
